name: Repo doctor

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Repository name (e.g. solidity-foundry-boilerplate)'
        required: true

jobs:
  repo_doctor:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Check out github repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.11.1

      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --network-concurrency 1

      - name: Repo doctor steps
        env:
          GH_OWNER: ${{ vars.GH_OWNER }}
          GH_APP_ID: ${{ vars.GH_APP_ID }}
          GH_INSTALLATION_ID: ${{ secrets.GH_INSTALLATION_ID }}
          GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GH_REPO_NAME: ${{ github.event.inputs.repo_name }}
          GH_USER_CREATOR: ${{ github.actor }}
          PAYLOAD: ${{ github.event.client_payload.message }}
        run: pnpm repo-doctor
